# Generated by Django 6.0 on 2026-01-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqitem',
            name='entry_method',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('PHOTO', 'Photo')], default='MANUAL', max_length=10),
        ),
    ]
