# Generated by Django 6.0 on 2026-01-05 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0003_vehiclemake_rfq_trim_alter_rfq_vin_vehiclemodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(db_index=True, help_text='Manufacturer part number', max_length=100)),
                ('part_name', models.CharField(help_text='Common name of the part', max_length=200)),
                ('year_from', models.PositiveIntegerField(blank=True, help_text='First compatible year', null=True)),
                ('year_to', models.PositiveIntegerField(blank=True, help_text='Last compatible year', null=True)),
                ('category', models.CharField(blank=True, help_text='e.g., Brake System, Engine', max_length=50)),
                ('manufacturer', models.CharField(blank=True, help_text='OEM or aftermarket brand', max_length=100)),
                ('is_oem', models.BooleanField(default=True, help_text='True if genuine OEM part')),
                ('alternative_numbers', models.TextField(blank=True, help_text='Comma-separated alternative part numbers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('make', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='rfqs.vehiclemake')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parts', to='rfqs.vehiclemodel')),
            ],
            options={
                'verbose_name': 'Part Catalog Entry',
                'verbose_name_plural': 'Part Catalog',
                'ordering': ['part_number'],
                'indexes': [models.Index(fields=['part_number'], name='rfqs_partca_part_nu_f6dafd_idx'), models.Index(fields=['make', 'model'], name='rfqs_partca_make_id_cb2784_idx'), models.Index(fields=['year_from', 'year_to'], name='rfqs_partca_year_fr_1998c5_idx')],
            },
        ),
    ]
