# Generated by Django 6.0 on 2026-01-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0004_partcatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfqitem',
            name='part_number',
            field=models.CharField(blank=True, help_text='OEM or aftermarket part number', max_length=100),
        ),
    ]
