# Generated by Django 6.0 on 2026-01-07 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0005_rfqitem_part_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number', max_length=17)),
                ('reg_city', models.CharField(blank=True, help_text='e.g., DHAKA METRO', max_length=50)),
                ('reg_series', models.CharField(blank=True, help_text='e.g., GHA, KA', max_length=10)),
                ('reg_number1', models.IntegerField(blank=True, help_text='First number part', null=True)),
                ('reg_number2', models.IntegerField(blank=True, help_text='Second number part', null=True)),
                ('make_id', models.IntegerField()),
                ('make_name', models.CharField(max_length=100)),
                ('model_id', models.IntegerField()),
                ('model_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('customer_name', models.CharField(help_text='Vehicle owner name', max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('nickname', models.CharField(blank=True, help_text="e.g., Dad's Car, Office Van", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Vehicle',
                'verbose_name_plural': 'Saved Vehicles',
                'ordering': ['-created_at'],
            },
        ),
    ]
