# Generated by Django 6.0 on 2026-01-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0006_savedvehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='reg_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='rfq',
            name='reg_number1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='reg_number2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='reg_series',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
