# Generated by Django 6.0 on 2026-01-07 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfqs', '0007_rfq_reg_city_rfq_reg_number1_rfq_reg_number2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='engine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='savedvehicle',
            name='engine',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='VehicleEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engines', to='rfqs.vehiclemodel')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('model', 'name')},
            },
        ),
    ]
