# Generated by Django 6.0 on 2026-01-03 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rfqs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('part_category', models.CharField(choices=[('GENUINE_OEM', 'Genuine OEM'), ('AFTERMARKET_BRANDED', 'Aftermarket (Branded)'), ('AFTERMARKET_UNBRANDED', 'Aftermarket (Unbranded)'), ('USED_RECONDITIONED', 'Used/Reconditioned')], max_length=30)),
                ('brand', models.CharField(blank=True, help_text='Brand name if applicable', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rfq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='rfqs.rfqitem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
