# Generated by Django 6.0 on 2026-01-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='availability',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bid',
            name='eta',
            field=models.CharField(blank=True, help_text='e.g. 2 hours, 1 day', max_length=50),
        ),
    ]
